DROP TABLE EVENTREQUEST;


CREATE TABLE EVENTREQUEST
(eventno CHAR(8),
dateheld DATE CONSTRAINT dateheldrequired NOT NULL,
datereq DATE CONSTRAINT datereqrequired NOT NULL,
facno VARCHAR(8),
custno VARCHAR(8),
dateauth DATE,
status VARCHAR(20),
estcost DECIMAL(8,2) CONSTRAINT estcostrequired NOT NULL,
estauidence CHAR(10) CONSTRAINT estaudience NOT NULL,
budno CHAR(10),
CONSTRAINT pkEVENTREQUEST PRIMARY KEY (eventno),
CONSTRAINT fkfacno FOREIGN KEY (facno) REFERENCES FACILITY,
CONSTRAINT fkcustno FOREIGN KEY (custno) REFERENCES CUSTOMER
);

