DROP TABLE EVENTPLANLINE;
DROP TABLE EVENTPLAN;
DROP TABLE EVENTREQUEST;
DROP TABLE RESOURCETBL;
DROP TABLE LOCATION;
DROP TABLE FACILITY;
DROP TABLE CUSTOMER;
DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE
(empno CHAR(8),
empname VARCHAR2(20) CONSTRAINT empnamerequired NOT NULL,
department VARCHAR2(20) CONSTRAINT departmentrequired NOT NULL,
email VARCHAR2(20) CONSTRAINT emailrequired NOT NULL,
phone CHAR(15) CONSTRAINT phonerequired NOT NULL,
CONSTRAINT pkEMPLOYEE PRIMARY KEY (empno) 
);

CREATE TABLE CUSTOMER
(custno VARCHAR2(8),
custname VARCHAR2(20)CONSTRAINT custnamerequired NOT NULL,
address  VARCHAR2(20) CONSTRAINT addressrequired NOT NULL,
internal CHAR(1) CONSTRAINT internalrequired NOT NULL,
contact VARCHAR2(20) CONSTRAINT contactrequired NOT NULL,
phone CHAR(15) CONSTRAINT phonenumberequired NOT NULL,
city VARCHAR2(20) CONSTRAINT citynamerequired NOT NULL,
state VARCHAR2(20) CONSTRAINT staterequired NOT NULL,
zip CHAR(10) CONSTRAINT zipnumberrequired NOT NULL,
CONSTRAINT pkCUSTOMER PRIMARY KEY(custno));

CREATE TABLE RESOURCETBL
(resno VARCHAR(8),
resname VARCHAR(20) CONSTRAINT resnamerequired NOT NULL,
rate CHAR(20) CONSTRAINT raterequired NOT NULL,
CONSTRAINT pkresno PRIMARY KEY (resno));


CREATE TABLE FACILITY 
(facno VARCHAR2(8),
facname VARCHAR2(20) CONSTRAINT facnamerequired NOT NULL,
CONSTRAINT pkFACILITY PRIMARY KEY (facno)
);

CREATE TABLE LOCATION
(locno VARCHAR2(8),
facno VARCHAR2(8),
locname VARCHAR2(20) CONSTRAINT locnamerequired NOT NULL,
CONSTRAINT pkLOCATION PRIMARY KEY (locno),
CONSTRAINT fkfacno FOREIGN KEY (facno) REFERENCES FACILITY);


CREATE TABLE EVENTREQUEST
(eventno VARCHAR2(8),
dateheld DATE CONSTRAINT dateheldrequired NOT NULL,
datereq DATE CONSTRAINT datereqrequired NOT NULL,
facno VARCHAR2(8),
custno VARCHAR2(8),
dateauth DATE,
status VARCHAR2(20),
estcost DECIMAL(8,2) CONSTRAINT estcostrequired NOT NULL,
estaudience CHAR(10) CONSTRAINT estaudiencerequired NOT NULL,
budno CHAR(10),
CONSTRAINT pkEVENTREQUEST PRIMARY KEY (eventno),
CONSTRAINT fkfacnoeve FOREIGN KEY (facno) REFERENCES FACILITY(facno),
CONSTRAINT fkcustno FOREIGN KEY (custno) REFERENCES CUSTOMER(custno),
CONSTRAINT checkstatus CHECK (status IN ('Pending','Denied','Approved') ),
CONSTRAINT checkestaudience CHECK (estaudience > 0)
);

CREATE TABLE EVENTPLAN
(planno VARCHAR2(8),
eventno VARCHAR2(8),
workdate DATE CONSTRAINT workdaterequired NOT NULL,
notes VARCHAR2(50),
activity VARCHAR2(10),
empno CHAR(10),
CONSTRAINT pkEVENTPLAN PRIMARY KEY (planno),
CONSTRAINT fkeventno FOREIGN KEY (eventno) REFERENCES EVENTREQUEST);


CREATE TABLE EVENTPLANLINE
(planno VARCHAR2(8),
lineno VARCHAR2(8),
TimeStart DATE CONSTRAINT TimeStartrequired NOT NULL,
TimeEnd DATE CONSTRAINT TimeEndrequired NOT NULL,
NumberFld CHAR(2) CONSTRAINT NumberFldrequired NOT NULL,
locno VARCHAR2(8),
resno VARCHAR2(8),
CONSTRAINT pklineno PRIMARY KEY (planno,lineno),
CONSTRAINT fkplannoevent FOREIGN KEY (planno) REFERENCES EVENTPLAN, 
CONSTRAINT fklocnoevent FOREIGN KEY (locno) REFERENCES LOCATION(locno),
CONSTRAINT fkresnoevent FOREIGN KEY (resno) REFERENCES RESOURCETBL(resno),
CONSTRAINT checkdate CHECK (TimeStart < TimeEnd)
);


