DROP TABLE LOCATION;


CREATE TABLE LOCATION
(locno CHAR(8),
facno CHAR(8),
locname VARCHAR(20) CONSTRAINT locnamerequired NOT NULL,
CONSTRAINT pkLOCATION PRIMARY KEY (locno),
CONSTRAINT fkfacno FOREIGN KEY (facno) REFERENCES FACILITY);
